### get signins
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "tester@gmail.com",
  "password": "123456"
}

### registera
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
  "email": "tester122@gmail.com",
  "password": "123456",
  "fullname": "Tester Name"
}

### get mes121
GET http://localhost:8080/api/v1/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDYwODkxMTAsImlkIjoxLCJuYmYiOjE3MDYwODkxMTB9.9T0bi3-TjKXBrOLS2LhoRZ2civy0DTS4pKObk-exlX4

